// Generated by gencpp from file robot_teleop/active_csp.msg
// DO NOT EDIT!


#ifndef ROBOT_TELEOP_MESSAGE_ACTIVE_CSP_H
#define ROBOT_TELEOP_MESSAGE_ACTIVE_CSP_H

#include <ros/service_traits.h>


#include <robot_teleop/active_cspRequest.h>
#include <robot_teleop/active_cspResponse.h>


namespace robot_teleop
{

struct active_csp
{

typedef active_cspRequest Request;
typedef active_cspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct active_csp
} // namespace robot_teleop


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_teleop::active_csp > {
  static const char* value()
  {
    return "9d17c7a086f295f3ddeb8ac344bfc6ca";
  }

  static const char* value(const ::robot_teleop::active_csp&) { return value(); }
};

template<>
struct DataType< ::robot_teleop::active_csp > {
  static const char* value()
  {
    return "robot_teleop/active_csp";
  }

  static const char* value(const ::robot_teleop::active_csp&) { return value(); }
};


// service_traits::MD5Sum< ::robot_teleop::active_cspRequest> should match
// service_traits::MD5Sum< ::robot_teleop::active_csp >
template<>
struct MD5Sum< ::robot_teleop::active_cspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_teleop::active_csp >::value();
  }
  static const char* value(const ::robot_teleop::active_cspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_teleop::active_cspRequest> should match
// service_traits::DataType< ::robot_teleop::active_csp >
template<>
struct DataType< ::robot_teleop::active_cspRequest>
{
  static const char* value()
  {
    return DataType< ::robot_teleop::active_csp >::value();
  }
  static const char* value(const ::robot_teleop::active_cspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_teleop::active_cspResponse> should match
// service_traits::MD5Sum< ::robot_teleop::active_csp >
template<>
struct MD5Sum< ::robot_teleop::active_cspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_teleop::active_csp >::value();
  }
  static const char* value(const ::robot_teleop::active_cspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_teleop::active_cspResponse> should match
// service_traits::DataType< ::robot_teleop::active_csp >
template<>
struct DataType< ::robot_teleop::active_cspResponse>
{
  static const char* value()
  {
    return DataType< ::robot_teleop::active_csp >::value();
  }
  static const char* value(const ::robot_teleop::active_cspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_TELEOP_MESSAGE_ACTIVE_CSP_H
