// Generated by gencpp from file robot_teleop/homeResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_TELEOP_MESSAGE_HOMERESPONSE_H
#define ROBOT_TELEOP_MESSAGE_HOMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_teleop
{
template <class ContainerAllocator>
struct homeResponse_
{
  typedef homeResponse_<ContainerAllocator> Type;

  homeResponse_()
    : result(0)  {
    }
  homeResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int16_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::robot_teleop::homeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_teleop::homeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct homeResponse_

typedef ::robot_teleop::homeResponse_<std::allocator<void> > homeResponse;

typedef boost::shared_ptr< ::robot_teleop::homeResponse > homeResponsePtr;
typedef boost::shared_ptr< ::robot_teleop::homeResponse const> homeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_teleop::homeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_teleop::homeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_teleop::homeResponse_<ContainerAllocator1> & lhs, const ::robot_teleop::homeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_teleop::homeResponse_<ContainerAllocator1> & lhs, const ::robot_teleop::homeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_teleop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_teleop::homeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_teleop::homeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_teleop::homeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_teleop::homeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_teleop::homeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_teleop::homeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_teleop::homeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2c2de4947863e4feccd94cb02ed28ea";
  }

  static const char* value(const ::robot_teleop::homeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2c2de4947863e4fULL;
  static const uint64_t static_value2 = 0xeccd94cb02ed28eaULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_teleop::homeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_teleop/homeResponse";
  }

  static const char* value(const ::robot_teleop::homeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_teleop::homeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 result\n"
"\n"
;
  }

  static const char* value(const ::robot_teleop::homeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_teleop::homeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct homeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_teleop::homeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_teleop::homeResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int16_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_TELEOP_MESSAGE_HOMERESPONSE_H
