// Generated by gencpp from file robot_teleop/home.msg
// DO NOT EDIT!


#ifndef ROBOT_TELEOP_MESSAGE_HOME_H
#define ROBOT_TELEOP_MESSAGE_HOME_H

#include <ros/service_traits.h>


#include <robot_teleop/homeRequest.h>
#include <robot_teleop/homeResponse.h>


namespace robot_teleop
{

struct home
{

typedef homeRequest Request;
typedef homeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct home
} // namespace robot_teleop


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_teleop::home > {
  static const char* value()
  {
    return "9d17c7a086f295f3ddeb8ac344bfc6ca";
  }

  static const char* value(const ::robot_teleop::home&) { return value(); }
};

template<>
struct DataType< ::robot_teleop::home > {
  static const char* value()
  {
    return "robot_teleop/home";
  }

  static const char* value(const ::robot_teleop::home&) { return value(); }
};


// service_traits::MD5Sum< ::robot_teleop::homeRequest> should match
// service_traits::MD5Sum< ::robot_teleop::home >
template<>
struct MD5Sum< ::robot_teleop::homeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_teleop::home >::value();
  }
  static const char* value(const ::robot_teleop::homeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_teleop::homeRequest> should match
// service_traits::DataType< ::robot_teleop::home >
template<>
struct DataType< ::robot_teleop::homeRequest>
{
  static const char* value()
  {
    return DataType< ::robot_teleop::home >::value();
  }
  static const char* value(const ::robot_teleop::homeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_teleop::homeResponse> should match
// service_traits::MD5Sum< ::robot_teleop::home >
template<>
struct MD5Sum< ::robot_teleop::homeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_teleop::home >::value();
  }
  static const char* value(const ::robot_teleop::homeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_teleop::homeResponse> should match
// service_traits::DataType< ::robot_teleop::home >
template<>
struct DataType< ::robot_teleop::homeResponse>
{
  static const char* value()
  {
    return DataType< ::robot_teleop::home >::value();
  }
  static const char* value(const ::robot_teleop::homeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_TELEOP_MESSAGE_HOME_H
