// Generated by gencpp from file robot_teleop/node.msg
// DO NOT EDIT!


#ifndef ROBOT_TELEOP_MESSAGE_NODE_H
#define ROBOT_TELEOP_MESSAGE_NODE_H

#include <ros/service_traits.h>


#include <robot_teleop/nodeRequest.h>
#include <robot_teleop/nodeResponse.h>


namespace robot_teleop
{

struct node
{

typedef nodeRequest Request;
typedef nodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node
} // namespace robot_teleop


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_teleop::node > {
  static const char* value()
  {
    return "0c471dfb6b81ef71ddb24300538963e0";
  }

  static const char* value(const ::robot_teleop::node&) { return value(); }
};

template<>
struct DataType< ::robot_teleop::node > {
  static const char* value()
  {
    return "robot_teleop/node";
  }

  static const char* value(const ::robot_teleop::node&) { return value(); }
};


// service_traits::MD5Sum< ::robot_teleop::nodeRequest> should match
// service_traits::MD5Sum< ::robot_teleop::node >
template<>
struct MD5Sum< ::robot_teleop::nodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_teleop::node >::value();
  }
  static const char* value(const ::robot_teleop::nodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_teleop::nodeRequest> should match
// service_traits::DataType< ::robot_teleop::node >
template<>
struct DataType< ::robot_teleop::nodeRequest>
{
  static const char* value()
  {
    return DataType< ::robot_teleop::node >::value();
  }
  static const char* value(const ::robot_teleop::nodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_teleop::nodeResponse> should match
// service_traits::MD5Sum< ::robot_teleop::node >
template<>
struct MD5Sum< ::robot_teleop::nodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_teleop::node >::value();
  }
  static const char* value(const ::robot_teleop::nodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_teleop::nodeResponse> should match
// service_traits::DataType< ::robot_teleop::node >
template<>
struct DataType< ::robot_teleop::nodeResponse>
{
  static const char* value()
  {
    return DataType< ::robot_teleop::node >::value();
  }
  static const char* value(const ::robot_teleop::nodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_TELEOP_MESSAGE_NODE_H
