// Generated by gencpp from file robot_teleop/nodeRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_TELEOP_MESSAGE_NODEREQUEST_H
#define ROBOT_TELEOP_MESSAGE_NODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_teleop
{
template <class ContainerAllocator>
struct nodeRequest_
{
  typedef nodeRequest_<ContainerAllocator> Type;

  nodeRequest_()
    : nodeID(0)  {
    }
  nodeRequest_(const ContainerAllocator& _alloc)
    : nodeID(0)  {
  (void)_alloc;
    }



   typedef int32_t _nodeID_type;
  _nodeID_type nodeID;





  typedef boost::shared_ptr< ::robot_teleop::nodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_teleop::nodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nodeRequest_

typedef ::robot_teleop::nodeRequest_<std::allocator<void> > nodeRequest;

typedef boost::shared_ptr< ::robot_teleop::nodeRequest > nodeRequestPtr;
typedef boost::shared_ptr< ::robot_teleop::nodeRequest const> nodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_teleop::nodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_teleop::nodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_teleop::nodeRequest_<ContainerAllocator1> & lhs, const ::robot_teleop::nodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.nodeID == rhs.nodeID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_teleop::nodeRequest_<ContainerAllocator1> & lhs, const ::robot_teleop::nodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_teleop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_teleop::nodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_teleop::nodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_teleop::nodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_teleop::nodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_teleop::nodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_teleop::nodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_teleop::nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83f1d0e77402d46c26211c4c64e0f71c";
  }

  static const char* value(const ::robot_teleop::nodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83f1d0e77402d46cULL;
  static const uint64_t static_value2 = 0x26211c4c64e0f71cULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_teleop::nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_teleop/nodeRequest";
  }

  static const char* value(const ::robot_teleop::nodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_teleop::nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 nodeID\n"
;
  }

  static const char* value(const ::robot_teleop::nodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_teleop::nodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodeID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_teleop::nodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_teleop::nodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "nodeID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nodeID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_TELEOP_MESSAGE_NODEREQUEST_H
