// Generated by gencpp from file robot_teleop/nodeResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_TELEOP_MESSAGE_NODERESPONSE_H
#define ROBOT_TELEOP_MESSAGE_NODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_teleop
{
template <class ContainerAllocator>
struct nodeResponse_
{
  typedef nodeResponse_<ContainerAllocator> Type;

  nodeResponse_()
    : result(0)  {
    }
  nodeResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::robot_teleop::nodeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_teleop::nodeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct nodeResponse_

typedef ::robot_teleop::nodeResponse_<std::allocator<void> > nodeResponse;

typedef boost::shared_ptr< ::robot_teleop::nodeResponse > nodeResponsePtr;
typedef boost::shared_ptr< ::robot_teleop::nodeResponse const> nodeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_teleop::nodeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_teleop::nodeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_teleop::nodeResponse_<ContainerAllocator1> & lhs, const ::robot_teleop::nodeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_teleop::nodeResponse_<ContainerAllocator1> & lhs, const ::robot_teleop::nodeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_teleop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_teleop::nodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_teleop::nodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_teleop::nodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_teleop::nodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_teleop::nodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_teleop::nodeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_teleop::nodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::robot_teleop::nodeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_teleop::nodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_teleop/nodeResponse";
  }

  static const char* value(const ::robot_teleop::nodeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_teleop::nodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"\n"
;
  }

  static const char* value(const ::robot_teleop::nodeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_teleop::nodeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nodeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_teleop::nodeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_teleop::nodeResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_TELEOP_MESSAGE_NODERESPONSE_H
