// Generated by gencpp from file robot_teleop/reset_node.msg
// DO NOT EDIT!


#ifndef ROBOT_TELEOP_MESSAGE_RESET_NODE_H
#define ROBOT_TELEOP_MESSAGE_RESET_NODE_H

#include <ros/service_traits.h>


#include <robot_teleop/reset_nodeRequest.h>
#include <robot_teleop/reset_nodeResponse.h>


namespace robot_teleop
{

struct reset_node
{

typedef reset_nodeRequest Request;
typedef reset_nodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset_node
} // namespace robot_teleop


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_teleop::reset_node > {
  static const char* value()
  {
    return "0c471dfb6b81ef71ddb24300538963e0";
  }

  static const char* value(const ::robot_teleop::reset_node&) { return value(); }
};

template<>
struct DataType< ::robot_teleop::reset_node > {
  static const char* value()
  {
    return "robot_teleop/reset_node";
  }

  static const char* value(const ::robot_teleop::reset_node&) { return value(); }
};


// service_traits::MD5Sum< ::robot_teleop::reset_nodeRequest> should match
// service_traits::MD5Sum< ::robot_teleop::reset_node >
template<>
struct MD5Sum< ::robot_teleop::reset_nodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_teleop::reset_node >::value();
  }
  static const char* value(const ::robot_teleop::reset_nodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_teleop::reset_nodeRequest> should match
// service_traits::DataType< ::robot_teleop::reset_node >
template<>
struct DataType< ::robot_teleop::reset_nodeRequest>
{
  static const char* value()
  {
    return DataType< ::robot_teleop::reset_node >::value();
  }
  static const char* value(const ::robot_teleop::reset_nodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_teleop::reset_nodeResponse> should match
// service_traits::MD5Sum< ::robot_teleop::reset_node >
template<>
struct MD5Sum< ::robot_teleop::reset_nodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_teleop::reset_node >::value();
  }
  static const char* value(const ::robot_teleop::reset_nodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_teleop::reset_nodeResponse> should match
// service_traits::DataType< ::robot_teleop::reset_node >
template<>
struct DataType< ::robot_teleop::reset_nodeResponse>
{
  static const char* value()
  {
    return DataType< ::robot_teleop::reset_node >::value();
  }
  static const char* value(const ::robot_teleop::reset_nodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_TELEOP_MESSAGE_RESET_NODE_H
