// Generated by gencpp from file surena_eth/active_csp.msg
// DO NOT EDIT!


#ifndef SURENA_ETH_MESSAGE_ACTIVE_CSP_H
#define SURENA_ETH_MESSAGE_ACTIVE_CSP_H

#include <ros/service_traits.h>


#include <surena_eth/active_cspRequest.h>
#include <surena_eth/active_cspResponse.h>


namespace surena_eth
{

struct active_csp
{

typedef active_cspRequest Request;
typedef active_cspResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct active_csp
} // namespace surena_eth


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::surena_eth::active_csp > {
  static const char* value()
  {
    return "9d17c7a086f295f3ddeb8ac344bfc6ca";
  }

  static const char* value(const ::surena_eth::active_csp&) { return value(); }
};

template<>
struct DataType< ::surena_eth::active_csp > {
  static const char* value()
  {
    return "surena_eth/active_csp";
  }

  static const char* value(const ::surena_eth::active_csp&) { return value(); }
};


// service_traits::MD5Sum< ::surena_eth::active_cspRequest> should match
// service_traits::MD5Sum< ::surena_eth::active_csp >
template<>
struct MD5Sum< ::surena_eth::active_cspRequest>
{
  static const char* value()
  {
    return MD5Sum< ::surena_eth::active_csp >::value();
  }
  static const char* value(const ::surena_eth::active_cspRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::surena_eth::active_cspRequest> should match
// service_traits::DataType< ::surena_eth::active_csp >
template<>
struct DataType< ::surena_eth::active_cspRequest>
{
  static const char* value()
  {
    return DataType< ::surena_eth::active_csp >::value();
  }
  static const char* value(const ::surena_eth::active_cspRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::surena_eth::active_cspResponse> should match
// service_traits::MD5Sum< ::surena_eth::active_csp >
template<>
struct MD5Sum< ::surena_eth::active_cspResponse>
{
  static const char* value()
  {
    return MD5Sum< ::surena_eth::active_csp >::value();
  }
  static const char* value(const ::surena_eth::active_cspResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::surena_eth::active_cspResponse> should match
// service_traits::DataType< ::surena_eth::active_csp >
template<>
struct DataType< ::surena_eth::active_cspResponse>
{
  static const char* value()
  {
    return DataType< ::surena_eth::active_csp >::value();
  }
  static const char* value(const ::surena_eth::active_cspResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SURENA_ETH_MESSAGE_ACTIVE_CSP_H
