// Generated by gencpp from file surena_eth/reset_node.msg
// DO NOT EDIT!


#ifndef SURENA_ETH_MESSAGE_RESET_NODE_H
#define SURENA_ETH_MESSAGE_RESET_NODE_H

#include <ros/service_traits.h>


#include <surena_eth/reset_nodeRequest.h>
#include <surena_eth/reset_nodeResponse.h>


namespace surena_eth
{

struct reset_node
{

typedef reset_nodeRequest Request;
typedef reset_nodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset_node
} // namespace surena_eth


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::surena_eth::reset_node > {
  static const char* value()
  {
    return "0c471dfb6b81ef71ddb24300538963e0";
  }

  static const char* value(const ::surena_eth::reset_node&) { return value(); }
};

template<>
struct DataType< ::surena_eth::reset_node > {
  static const char* value()
  {
    return "surena_eth/reset_node";
  }

  static const char* value(const ::surena_eth::reset_node&) { return value(); }
};


// service_traits::MD5Sum< ::surena_eth::reset_nodeRequest> should match
// service_traits::MD5Sum< ::surena_eth::reset_node >
template<>
struct MD5Sum< ::surena_eth::reset_nodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::surena_eth::reset_node >::value();
  }
  static const char* value(const ::surena_eth::reset_nodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::surena_eth::reset_nodeRequest> should match
// service_traits::DataType< ::surena_eth::reset_node >
template<>
struct DataType< ::surena_eth::reset_nodeRequest>
{
  static const char* value()
  {
    return DataType< ::surena_eth::reset_node >::value();
  }
  static const char* value(const ::surena_eth::reset_nodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::surena_eth::reset_nodeResponse> should match
// service_traits::MD5Sum< ::surena_eth::reset_node >
template<>
struct MD5Sum< ::surena_eth::reset_nodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::surena_eth::reset_node >::value();
  }
  static const char* value(const ::surena_eth::reset_nodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::surena_eth::reset_nodeResponse> should match
// service_traits::DataType< ::surena_eth::reset_node >
template<>
struct DataType< ::surena_eth::reset_nodeResponse>
{
  static const char* value()
  {
    return DataType< ::surena_eth::reset_node >::value();
  }
  static const char* value(const ::surena_eth::reset_nodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SURENA_ETH_MESSAGE_RESET_NODE_H
