// Generated by gencpp from file surena_eth/reset_nodeRequest.msg
// DO NOT EDIT!


#ifndef SURENA_ETH_MESSAGE_RESET_NODEREQUEST_H
#define SURENA_ETH_MESSAGE_RESET_NODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace surena_eth
{
template <class ContainerAllocator>
struct reset_nodeRequest_
{
  typedef reset_nodeRequest_<ContainerAllocator> Type;

  reset_nodeRequest_()
    : nodeID(0)  {
    }
  reset_nodeRequest_(const ContainerAllocator& _alloc)
    : nodeID(0)  {
  (void)_alloc;
    }



   typedef int32_t _nodeID_type;
  _nodeID_type nodeID;





  typedef boost::shared_ptr< ::surena_eth::reset_nodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::surena_eth::reset_nodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct reset_nodeRequest_

typedef ::surena_eth::reset_nodeRequest_<std::allocator<void> > reset_nodeRequest;

typedef boost::shared_ptr< ::surena_eth::reset_nodeRequest > reset_nodeRequestPtr;
typedef boost::shared_ptr< ::surena_eth::reset_nodeRequest const> reset_nodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::surena_eth::reset_nodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::surena_eth::reset_nodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::surena_eth::reset_nodeRequest_<ContainerAllocator1> & lhs, const ::surena_eth::reset_nodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.nodeID == rhs.nodeID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::surena_eth::reset_nodeRequest_<ContainerAllocator1> & lhs, const ::surena_eth::reset_nodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace surena_eth

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::surena_eth::reset_nodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::surena_eth::reset_nodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::surena_eth::reset_nodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::surena_eth::reset_nodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::surena_eth::reset_nodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::surena_eth::reset_nodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::surena_eth::reset_nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83f1d0e77402d46c26211c4c64e0f71c";
  }

  static const char* value(const ::surena_eth::reset_nodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83f1d0e77402d46cULL;
  static const uint64_t static_value2 = 0x26211c4c64e0f71cULL;
};

template<class ContainerAllocator>
struct DataType< ::surena_eth::reset_nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "surena_eth/reset_nodeRequest";
  }

  static const char* value(const ::surena_eth::reset_nodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::surena_eth::reset_nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 nodeID\n"
;
  }

  static const char* value(const ::surena_eth::reset_nodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::surena_eth::reset_nodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodeID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reset_nodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::surena_eth::reset_nodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::surena_eth::reset_nodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "nodeID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.nodeID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SURENA_ETH_MESSAGE_RESET_NODEREQUEST_H
