// Generated by gencpp from file surena_eth/set_led.msg
// DO NOT EDIT!


#ifndef SURENA_ETH_MESSAGE_SET_LED_H
#define SURENA_ETH_MESSAGE_SET_LED_H

#include <ros/service_traits.h>


#include <surena_eth/set_ledRequest.h>
#include <surena_eth/set_ledResponse.h>


namespace surena_eth
{

struct set_led
{

typedef set_ledRequest Request;
typedef set_ledResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_led
} // namespace surena_eth


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::surena_eth::set_led > {
  static const char* value()
  {
    return "e25c7994b68742a69959bfbdd1390188";
  }

  static const char* value(const ::surena_eth::set_led&) { return value(); }
};

template<>
struct DataType< ::surena_eth::set_led > {
  static const char* value()
  {
    return "surena_eth/set_led";
  }

  static const char* value(const ::surena_eth::set_led&) { return value(); }
};


// service_traits::MD5Sum< ::surena_eth::set_ledRequest> should match
// service_traits::MD5Sum< ::surena_eth::set_led >
template<>
struct MD5Sum< ::surena_eth::set_ledRequest>
{
  static const char* value()
  {
    return MD5Sum< ::surena_eth::set_led >::value();
  }
  static const char* value(const ::surena_eth::set_ledRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::surena_eth::set_ledRequest> should match
// service_traits::DataType< ::surena_eth::set_led >
template<>
struct DataType< ::surena_eth::set_ledRequest>
{
  static const char* value()
  {
    return DataType< ::surena_eth::set_led >::value();
  }
  static const char* value(const ::surena_eth::set_ledRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::surena_eth::set_ledResponse> should match
// service_traits::MD5Sum< ::surena_eth::set_led >
template<>
struct MD5Sum< ::surena_eth::set_ledResponse>
{
  static const char* value()
  {
    return MD5Sum< ::surena_eth::set_led >::value();
  }
  static const char* value(const ::surena_eth::set_ledResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::surena_eth::set_ledResponse> should match
// service_traits::DataType< ::surena_eth::set_led >
template<>
struct DataType< ::surena_eth::set_ledResponse>
{
  static const char* value()
  {
    return DataType< ::surena_eth::set_led >::value();
  }
  static const char* value(const ::surena_eth::set_ledResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SURENA_ETH_MESSAGE_SET_LED_H
