// Generated by gencpp from file offlinepublisher/srv1Response.msg
// DO NOT EDIT!


#ifndef OFFLINEPUBLISHER_MESSAGE_SRV1RESPONSE_H
#define OFFLINEPUBLISHER_MESSAGE_SRV1RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offlinepublisher
{
template <class ContainerAllocator>
struct srv1Response_
{
  typedef srv1Response_<ContainerAllocator> Type;

  srv1Response_()
    : sum(0)  {
    }
  srv1Response_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::offlinepublisher::srv1Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offlinepublisher::srv1Response_<ContainerAllocator> const> ConstPtr;

}; // struct srv1Response_

typedef ::offlinepublisher::srv1Response_<std::allocator<void> > srv1Response;

typedef boost::shared_ptr< ::offlinepublisher::srv1Response > srv1ResponsePtr;
typedef boost::shared_ptr< ::offlinepublisher::srv1Response const> srv1ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offlinepublisher::srv1Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offlinepublisher::srv1Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offlinepublisher::srv1Response_<ContainerAllocator1> & lhs, const ::offlinepublisher::srv1Response_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offlinepublisher::srv1Response_<ContainerAllocator1> & lhs, const ::offlinepublisher::srv1Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offlinepublisher

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::offlinepublisher::srv1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offlinepublisher::srv1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offlinepublisher::srv1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offlinepublisher::srv1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offlinepublisher::srv1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offlinepublisher::srv1Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offlinepublisher::srv1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::offlinepublisher::srv1Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::offlinepublisher::srv1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offlinepublisher/srv1Response";
  }

  static const char* value(const ::offlinepublisher::srv1Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offlinepublisher::srv1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
"\n"
;
  }

  static const char* value(const ::offlinepublisher::srv1Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offlinepublisher::srv1Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv1Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offlinepublisher::srv1Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offlinepublisher::srv1Response_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFLINEPUBLISHER_MESSAGE_SRV1RESPONSE_H
